2024-04-12: back option

diff --git a/Scripts/findopen_mac b/Scripts/findopen_mac
--- a/Scripts/findopen_mac
+++ b/Scripts/findopen_mac
@@ -12,7 +12,6 @@ copy_directory_path() {
     local target_path="$1"
     echo -n "$target_path" | pbcopy  # On macOS, we use pbcopy to copy to the clipboard
     echo "Directory path copied to clipboard: $target_path"
-    sleep 2
 }
 
 # Function to format all .c and .h files in a directory and its subdirectories
@@ -28,6 +27,13 @@ format_directory() {
     echo "Formatting in $directory complete."
 }
 
+# Function to navigate to a directory in terminal
+navigate_to_directory() {
+    local target_path="$1"
+    cd "$target_path" || { echo "Failed to navigate to directory."; exit 1; }
+    echo "Navigated to directory: $target_path"
+}
+
 # Function to prompt user for action
 prompt_action() {
     local target_path="$1"
@@ -37,13 +43,14 @@ prompt_action() {
         echo -e "\033[1m\033[32m2: \033[0mFormat files with C_Formatter_42"
         echo -e "\033[1m\033[32m3: \033[0mNavigate to Directory in Terminal"
         echo -e "\033[1m\033[32m4: \033[0mCopy Directory"
-        echo -e "\033[1m\033[31m0: \033[0mReturn to selection prompt menu"
+        echo -e "\033[1m\033[31m9: \033[0mBack"
+        echo -e "\033[1m\033[31m0: \033[0mExit"
         read -rp $'\033[1mChoice: \033[0m' action_choice
 
         case "$action_choice" in
             0)
-                echo "Returning to selection prompt menu."
-                break
+                echo "Exiting."
+                exit 0
                 ;;
             1)
                 open_in_vscode "$target_path"
@@ -52,14 +59,36 @@ prompt_action() {
                 format_directory "$target_path"
                 ;;
             3)
-                cd "$target_path" || { echo "Failed to navigate to directory."; exit 1; }
-                echo "Navigated to directory: $target_path"
+                navigate_to_directory "$target_path"
                 ;;
             4)
                 copy_directory_path "$target_path"
                 ;;
+            9)
+                return 1  # Return flag indicating back to the caller function
+                ;;
             *)
                 echo "Invalid choice."
+                ;;
+        esac
+
+        # Ask if user wants to perform another action or exit
+        sleep 1
+        echo -e "\033[1mDo you want to perform another action or exit?\033[0m"
+        echo -e "\033[1m\033[32m1: \033[0mTry again"
+        echo -e "\033[1m\033[31m0: \033[0mExit"
+        read -rp $'\033[1mChoice: \033[0m' continue_choice
+        case "$continue_choice" in
+            0)
+                echo "Exiting."
+                exit 0
+                ;;
+            1)
+                break
+                ;;
+            *)
+                echo "Invalid choice. Exiting."
+                exit 1
                 ;;
         esac
     done
@@ -89,7 +118,8 @@ list_files_and_folders() {
 
     # Print the list of files and folders
     printf "\033[1mFiles and folders with the name '%s':\033[0m\n" "$search_name"
-    printf "\033[1m\033[31m0: EXIT\033[0m\n" # Exit option in bold red
+    printf "\033[1m\033[31m9: \033[0mBack\n" # Back option in red
+    printf "\033[1m\033[31m0: \033[0mExit\n" # Exit option in red
     for (( i=0; i<"${#files[@]}"; i++ )); do
         printf "\033[1m\033[32m%d: \033[0m\033[95m\"%s\"\033[0m\n" $((i+1)) "${files[$i]}"  # Green color for numbers, pink for files
     done
@@ -105,6 +135,8 @@ list_files_and_folders() {
         if [ "$choice" -eq 0 ]; then
             echo -e "\033[1m\033[31mExiting.\033[0m"
             exit 0
+        elif [ "$choice" -eq 9 ]; then
+            return 0  # Return flag indicating back to the caller function
         elif [ "$choice" -le "${#files[@]}" ]; then
             local selected_file="${files[$((choice-1))]}"
             echo "Selected file: $selected_file"
@@ -139,7 +171,10 @@ main() {
     search_name="$1"
 
     # List files and folders with the specified name
-    list_files_and_folders "$search_name" "${base_directories[@]}"
+    while true; do
+        list_files_and_folders "$search_name" "${base_directories[@]}"
+        echo "Returning to directory selection..."
+    done
 }
 
 main "$@"
